#!/bin/sh

# exec 2>&1
exec "$CATALINA_HOME/bin/startup.sh"

# sleep 10
# tail  /usr/local/tomcat/logs/catalina.out

# cd $WORKDIR
# ./load_exist.pl --user admin  --host-port localhost:8080 --load . --context /exist/rest/db/dcm --suffix xml,xq,xqm,css,xsl
